### ISSUE TITLE
运行报错了，能请教一下是什么问题吗？

### ISSUE THREAD

**Issue by YeYuDao** [hokaso/douyin2bilibili#3]
Traceback (most recent call last):
  File "D:\python_project\python_test\douyin2bilibili_streamline.py", line 538, in <module>
    douyin.run()
  File "D:\python_project\python_test\douyin2bilibili_streamline.py", line 223, in run
    video_name, video_url, nickname, nicklogo, flag = self.parse_douyin(share_url)
  File "D:\python_project\python_test\douyin2bilibili_streamline.py", line 105, in parse_douyin
    playurl = re.findall('playAddr:(.*?)\,', str(rct.text))[0]
IndexError: list index out of range

**Comment by hb19890430** [comment]
list index out of range,feedback data is null.




At 2021-01-14 14:05:30, "YeYuDao" <notifications@github.com> wrote:

Traceback (most recent call last):
File "D:\python_project\python_test\douyin2bilibili_streamline.py", line 538, in
douyin.run()
File "D:\python_project\python_test\douyin2bilibili_streamline.py", line 223, in run
video_name, video_url, nickname, nicklogo, flag = self.parse_douyin(share_url)
File "D:\python_project\python_test\douyin2bilibili_streamline.py", line 105, in parse_douyin
playurl = re.findall('playAddr:(.*?),', str(rct.text))[0]
IndexError: list index out of range
